[[kernelarch]]
name = 'alpha'
  [[kernelarch.debianarch]]
  name = 'alpha'

[[kernelarch]]
name = 'arc'
  [[kernelarch.debianarch]]
  name = 'arc'
    [kernelarch.debianarch.packages]
    libc_dev_cross_only = true

[[kernelarch]]
name = 'arm'
  [[kernelarch.debianarch]]
  name = 'armel'
  [[kernelarch.debianarch]]
  name = 'armhf'

[[kernelarch]]
name = 'arm64'
  [[kernelarch.debianarch]]
  name = 'arm64'

[[kernelarch]]
name = 'parisc'
  [[kernelarch.debianarch]]
  name = 'hppa'

[[kernelarch]]
name = 'loongarch'
  [[kernelarch.debianarch]]
  name = 'loong64'

[[kernelarch]]
name = 'm68k'
  [[kernelarch.debianarch]]
  name = 'm68k'

[[kernelarch]]
name = 'mips'
  [[kernelarch.debianarch]]
  name = 'mips'
  [[kernelarch.debianarch]]
  name = 'mips64'
  [[kernelarch.debianarch]]
  name = 'mips64r6'
    [kernelarch.debianarch.packages]
    libc_dev_cross_only = true
  [[kernelarch.debianarch]]
  name = 'mips64el'
  [[kernelarch.debianarch]]
  name = 'mips64r6el'
  [[kernelarch.debianarch]]
  name = 'mipsel'
  [[kernelarch.debianarch]]
  name = 'mipsn32'
    [kernelarch.debianarch.packages]
    libc_dev_cross_only = true
  [[kernelarch.debianarch]]
  name = 'mipsn32el'
    [kernelarch.debianarch.packages]
    libc_dev_cross_only = true
  [[kernelarch.debianarch]]
  name = 'mipsn32r6'
    [kernelarch.debianarch.packages]
    libc_dev_cross_only = true
  [[kernelarch.debianarch]]
  name = 'mipsn32r6el'
    [kernelarch.debianarch.packages]
    libc_dev_cross_only = true
  [[kernelarch.debianarch]]
  name = 'mipsr6'
    [kernelarch.debianarch.packages]
    libc_dev_cross_only = true
  [[kernelarch.debianarch]]
  name = 'mipsr6el'
    [kernelarch.debianarch.packages]
    libc_dev_cross_only = true

[[kernelarch]]
name = 'powerpc'
  [[kernelarch.debianarch]]
  name = 'powerpc'
  [[kernelarch.debianarch]]
  name = 'ppc64'
  [[kernelarch.debianarch]]
  name = 'ppc64el'

[[kernelarch]]
name = 'riscv'
  [[kernelarch.debianarch]]
  name = 'riscv64'

[[kernelarch]]
name = 's390'
  [[kernelarch.debianarch]]
  name = 's390x'

[[kernelarch]]
name = 'sh'
  [[kernelarch.debianarch]]
  name = 'sh4'

[[kernelarch]]
name = 'sparc'
  [[kernelarch.debianarch]]
  name = 'sparc64'

[[kernelarch]]
name = 'x86'
  [[kernelarch.debianarch]]
  name = 'amd64'
  [[kernelarch.debianarch]]
  name = 'i386'
  [[kernelarch.debianarch]]
  name = 'x32'

[[featureset]]
name = 'none'

[[debianrelease]]
name_regex = 'UNRELEASED'
abi_version_full = false
abi_suffix = '+unreleased'

[[debianrelease]]
name_regex = 'experimental'
abi_version_full = false
revision_regex = '\d+~exp\d+'

[[debianrelease]]
name_regex = 'unstable'
abi_suffix = '+deb14'
revision_regex = '\d+(\.\d+)?'

[[debianrelease]]
name_regex = 'forky(-security)?'
abi_suffix = '+deb14'
revision_regex = '\d+(\.\d+)?(\+deb14u\d+)?'

[[debianrelease]]
name_regex = 'trixie-backports'
abi_suffix = '+deb13'
revision_regex = '\d+(\.\d+)?(\+deb14u\d+)?~bpo13\+\d+'

[[debianrelease]]
name_regex = 'trixie(-security)?'
abi_suffix = '+deb13'
revision_regex = '\d+(\.\d+)?(\+deb13u\d+)?'

[[debianrelease]]
name_regex = 'bookworm-backports'
abi_suffix = '+deb12'
revision_regex = '\d+(\.\d+)?(\+deb13u\d+)?~bpo12\+\d+'

# Use default rules for any suite with no explicit config
[[debianrelease]]
name_regex = '.*'

[description.long]
rt = 'This kernel is configured with PREEMPT_RT real time support.'
[description.short]
rt = 'PREEMPT_RT'

[build]
c_compiler = 'gcc-15'
rust_build_depends = [
  'rustc:native (>= 1.78.0)',
  'bindgen:native (>= 0.65.1)',
  'rust-src (>= 1.78.0)',
]

[relations.image]
depends = [
  'dracut | initramfs-tools (>= 0.120+deb8u2) | linux-initramfs-tool',
]
recommends = [
  'apparmor',
]
breaks = [
  'fwupdate (<< 12-7)',
  'wireless-regdb (<< 2019.06.03-1~)',
]
