[[flavour]]
name = 'arm64'
[flavour.defs]
is_default = true
[flavour.description]
hardware = '64-bit ARMv8 machines'
[flavour.packages]
installer = true

[[flavour]]
name = 'cloud-arm64'
[flavour.build]
config = ['config.cloud']
[flavour.description]
hardware = 'arm64 cloud'
hardware_long = 'cloud platforms supporting arm64 virtual machines'

[[flavour]]
name = 'arm64-16k'
[flavour.build]
config = ['arm64/config-page-16k']
[flavour.description]
hardware = '64-bit ARMv8 machines with 16k pages'

[[flavour]]
name = 'rt-arm64'
[flavour.build]
config = ['config.rt']
[flavour.description]
hardware = '64-bit ARMv8 machines'
parts = ['rt']

[[flavour]]
name = 'test'
[flavour.build]
config = ['config.test', 'arm64/config.test']
[flavour.defs]
is_test = true
[flavour.packages]
installer = true

[[featureset]]
name = 'none'

[build]
compiler_gnutype_compat = 'arm-linux-gnueabihf'
enable_dtb = true
enable_rust = true
enable_signed = true
kernel_file = 'arch/arm64/boot/Image'
kernel_stem = 'vmlinuz'

[relations.image]
breaks = [
  'u-boot-efi-dtb (<< 5~)',
  'reform-tools (<< 1.83~)',
  'flash-kernel (<< 3.110~)',
]
