name: Build Debian Kernel (SavarezOS)

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Force Python
        run: |
          python3 --version
          which python3

      - name: Setup swap
        run: |
          sudo fallocate -l 8G /swapfile
          sudo chmod 600 /swapfile
          sudo mkswap /swapfile
          sudo swapon /swapfile
          free -h

      - name: Install build dependencies
        run: |
          sudo apt update
          sudo apt install -y \
            build-essential \
            fakeroot \
            devscripts \
            debhelper \
            bc \
            bison \
            flex \
            libssl-dev \
            libelf-dev \
            dwarves \
            rsync \
            git \
            python3-pip \
            libncurses-dev \
            xz-utils \
            kmod

      - name: Prepare build
        run: |
          dpkg-parsechangelog
          chmod +x debian/rules

      - name: Build Debian kernel packages
        run: |
          fakeroot make -f debian/rules binary

      - name: Collect packages
        run: |
          mkdir out
          mv ../*.deb out/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: savarez-kernel-deb
          path: out/
